keys:
  # PGP KEY
  - &main       7D2F4C6B9A8300CCDDB641FDDF14B55A7A29C30F
# FIXME: adding age key and what is a main key?
  - &vanessa    age1ncepfcrzfep624tpanhqfflafznh7ftuqffv0nfq24jhv3dwx40sltjkad

creation_rules:
  - path_regex: ^secrets/common\.yaml$
    key_groups:
    - pgp:
      - *main
      age:
      - *vanessa
  - path_regex: ^secrets/vanessa\.yaml$
    key_groups:
    - pgp:
      - *main
      age:
      - *vanessa
