# nvfetcher.toml
[ligature-el]
src.git = "https://github.com/mickeynp/ligature.el.git"
fetch.git = "https://github.com/mickeynp/ligature.el.git"

[pyim-greatdict]
src.git = "https://github.com/tumashu/pyim-greatdict.git"
fetch.git = "https://github.com/tumashu/pyim-greatdict.git"

[telega-el]
src.git = "https://github.com/zevlg/telega.el.git"
fetch.git = "https://github.com/zevlg/telega.el.git"
