name: "Automatic update"
on:
  schedule:
    # every day 00:00 +08:00
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        ref: main
        token: '${{ secrets.PAT_FOR_AUTOMATED_UPDATE }}'
    - name: Install nix
      uses: cachix/install-nix-action@master
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/latest/download/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Setup cachix
      uses: cachix/cachix-action@master
      with:
        name: linyinfeng
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Set swap space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10
    - name: Nix flake update
      run: |
        nix flake update
    - name: Update pkgs
      run: |
        nix develop --command nvfetcher
    - name: Test evaluation
      run: |
        set -e
        system=$(nix eval --impure --raw  --expr "builtins.currentSystem")
        checks=$(nix eval --impure --json --expr "builtins.attrNames (builtins.getFlake \"$PWD\").checks.$system")
        for check in $(echo "$checks" | jq -r '.[]'); do
          echo "--- eval .#checks.$system.$check"
          nix eval --raw .#checks.$system.$check --accept-flake-config
          echo # add a new line
        done
    - name: Commit and push
      run: |
        if [ -z "$(git status --porcelain)" ]; then
          echo "repository is clean, skip commit and push"
        else
          git config --global user.email "nano@linyinfeng.com"
          git config --global user.name "Nano"
          git add --all
          git commit --message "Nix flake update"
          git push
        fi
